[supervisord]
nodaemon=true

[program:backend]
command=node /app/backend/dist/server.js
directory=/app/backend
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
